name: test_app
description: "Ma sante dans mon sac - Flutter application"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.9.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  intl: any
  google_fonts: ^6.3.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  introduction_screen: ^4.0.0
  smooth_page_indicator: ^1.2.1
  flutter_gen: ^5.12.0
  device_preview: ^1.2.0
  msix: ^3.16.12
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true
  uses-material-design: true
 
  # To add assets to your application, add an assets section, like this:
  assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  - images/first-aid-kit.gif
  - images/cut.png
  - images/infection.png
  - images/sunburn.png
  - images/frostbite.png
  - images/rash.png
  - images/bandage-roll.png
  - images/band-aid.png
  - images/body-lotion.png
  - images/diabetic-foot.png
  - images/question.png
  - images/symptoms.png
  - images/treatment.png
  - images/heal.png
  - images/prevention.png
  - images/bite.png
  - images/warning.png
  - images/burn.png
  - images/summer.png
  - images/winter.png
  - images/cutefeet.png
  - images/cutenail.png

  - images/wounds_instructions/magnifier.png 
  - images/wounds_instructions/wound_size.png
  - images/wounds_instructions/subcutaneous.png
  - images/wounds_instructions/dirtyhand.png
  - images/wounds_instructions/toomuchbleeding.png
  - images/wounds_instructions/hand-washing.png
  - images/wounds_instructions/drying-hands.png
  - images/wounds_instructions/bandage.png
  - images/wounds_instructions/donotuse.png
  - images/wounds_instructions/discharge.png
  - images/wounds_instructions/hospital.png
  - images/wounds_instructions/cool-down.png
  - images/wounds_instructions/burn-clothes.png
  - images/wounds_instructions/bitesimple.png
  - images/wounds_instructions/compressandroll.png
  - images/wounds_instructions/compressandtape.png
  - images/wounds_instructions/dressinghowto.png

  - images/graphic_images/infection1.png
  - images/graphic_images/infection2.png
  - images/graphic_images/infection3.png
  - images/graphic_images/infection4.png
  - images/graphic_images/infection5.png
  - images/graphic_images/infection6.png

  - images/graphic_images/dischargeClear.png
  - images/graphic_images/dischargePink.png
  - images/graphic_images/dischargeRed.png
  - images/graphic_images/dischargePus.png

  - images/graphic_images/laceration1.png
  - images/graphic_images/laceration2.png
  - images/graphic_images/laceration3.png

  - images/graphic_images/minorcut1.png
  - images/graphic_images/minorcut2.png
  - images/graphic_images/minorcut3.png     
  - images/graphic_images/minorcut4.png
  - images/graphic_images/minorcut5.png

  - images/graphic_images/athletefoot1.png
  - images/graphic_images/athletefoot2.png
  - images/graphic_images/athletefoot3.png
  - images/graphic_images/athletefoot4.png
  - images/graphic_images/athletefoot5.png
  - images/graphic_images/athletefoot6.png

  - images/graphic_images/nailfungus1.png
  - images/graphic_images/nailfungus2.png
  - images/graphic_images/nailfungus3.png
  - images/graphic_images/nailfungus4.png

  - images/graphic_images/cc1.png
  - images/graphic_images/cc2.png
  - images/graphic_images/cc3.png
  - images/graphic_images/cc4.png
  - images/graphic_images/cc5.png
  - images/graphic_images/cc6.png

  - images/graphic_images/blister1.png
  - images/graphic_images/blister2.png
  - images/graphic_images/blister3.png
  - images/graphic_images/blister4.png
  - images/graphic_images/blister5.png
  - images/graphic_images/blister6.png

  - images/graphic_images/immersionfoot1.png
  - images/graphic_images/immersionfoot2.png
  - images/graphic_images/immersionfoot3.png
  - images/graphic_images/immersionfoot4.png
  - images/graphic_images/immersionfoot5.png

  - images/graphic_images/ingrownnail1.png
  - images/graphic_images/ingrownnail2.png
  - images/graphic_images/ingrownnail3.png

  - images/graphic_images/bite1.png
  - images/graphic_images/bite2.png
  - images/graphic_images/bite3.png

  - images/graphic_images/1degree1.png
  - images/graphic_images/1degree2.png
  - images/graphic_images/1degree3.png
  - images/graphic_images/2degree2.png
  - images/graphic_images/2degree3.png
  - images/graphic_images/2degree4.png
  - images/graphic_images/2degree5.png
  - images/graphic_images/3degree1.png
  - images/graphic_images/3degree2.png
  - images/graphic_images/3degree3.png

  - images/graphic_images/degree1frost1.png
  - images/graphic_images/degree1frost2.png
  - images/graphic_images/degree1frost3.png
  - images/graphic_images/degree2frost1.png
  - images/graphic_images/degree2frost2.png
  - images/graphic_images/degree2frost3.png
  - images/graphic_images/degree3frost1.png
  - images/graphic_images/degree3frost2.png
  - images/graphic_images/degree4frost1.png
  - images/graphic_images/degree4frost2.png
  - images/graphic_images/thaw.png

  - images/graphic_images/sunburn2.png
  - images/graphic_images/sunburn3.png
  - images/graphic_images/sunburn4.png
  - images/graphic_images/sunburn5.png
  - images/graphic_images/sunburn6.png
  
  - images/feet_instructions/callus.png
  - images/feet_instructions/trenchfoot.png
  - images/feet_instructions/blister.png
  - images/feet_instructions/ingrownnail.png
  - images/feet_instructions/nailfungus.png
  - images/feet_instructions/footfungus.png
  - images/feet_instructions/howtocut.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
